version: '3'
volumes:
  db-data:
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "${PORT}:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=${WEB}
  web:
    build: "web"
    expose:
      - "80"
    ports:
      - "${XDEBUG_PORT}:9000"
    volumes:
      - ./web:/web
    links:
      - db:mysql
      - mailhog:mailhog
    environment:
      - VIRTUAL_HOST=${WEB}
      - XDEBUG_CONFIG=remote_host=172.18.0.4
      - NR_INSTALL_KEY=${NEWRELIC_KEY}
      - NR_INSTALL_SILENT=1
      - NR_APP_NAME=${APP_NAME}
    working_dir: /web
  db:
    build: "db"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
  composer:
    image: composer/composer
    volumes:
      - ./web:/web
    working_dir: /web
  drush:
    image: drush/drush:8
    volumes:
      - ./web:/web
    links:
      - db:mysql
    working_dir: /web/docroot
  drupal:
    build: drupal-console
    volumes:
      - ./web:/web
    links:
      - db:mysql
    working_dir: /web/docroot
  pma:
    image: "phpmyadmin/phpmyadmin"
    expose:
      - "80"
    links:
      - db:mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=app
      - PMA_PASSWORD=app
      - VIRTUAL_HOST=${PMA}
  mailhog:
    image: "mailhog/mailhog"
    expose:
      - "1025"
      - "8025"
    environment:
      - VIRTUAL_HOST=${MAILHOG}
      - VIRTUAL_PORT=8025
