version: '3'
volumes:
  mysql-data:
services:
  httpd:
    build: ./services/httpd
    ports:
      - "80"
      - "443"
    volumes:
      - ./www:/usr/local/apache2/htdocs
    links:
      - php:php
  php:
    build: ./services/php
    volumes:
      - ./www:/usr/local/apache2/htdocs
    links:
      - mysql:db
      - mailhog:mailhog
      - blackfire:blackfire
  mysql:
    build: ./services/mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  blackfire:
    image: blackfire/blackfire:latest
    environment:
      - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID}
      - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "80"
    links:
      - mysql:db
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025"
      - "8025"
