version: '3'
services:
  web:
    build: "web"
    ports:
      - "80:80"
    volumes:
      - ./web/drupal:/web
      - ./web/sites-enabled:/etc/apache2/sites-enabled/
    links:
      - db:mysql
  db:
    image: "mariadb:5.5.55"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=app
  drush:
    image: drush/drush:8
    volumes:
      - ./web/drupal:/web
    links:
      - db:mysql
  console:
    image: "drupalconsole/console:1.0"
    volumes:
      - ./web/drupal:/web
    links:
      - db:mysql
